/*
    Think of random numbers generated by math.random() as outcomes as below
    ROCK - 1
    PAPER - 2
    SCISSOR - 3
*/

// These will be updated as per wins
let humanScore = 0;
let computerScore = 0;
let round = 1;      // To count the rounds till game finishes

// To get the random outcome of the three outcomes of this game
function getComputerChoice () {

    // generates a number between 1–3 (inclusive)
    let assumption = Math.floor(Math.random() * 3 + 1);

    if (assumption === 1) {
        return "rock";
    }
    if (assumption === 2) {
        return "paper";
    }
    if (assumption === 3) {
        return "scissor";
    }

}

// Function to run the game for 1 round and update scores
function playRound (computerChoice, humanChoice, round) {

    // Case: When both the choices are same i.e, rock/paper/scissor
    if (computerChoice === humanChoice) {
        // No increment of score as it's draw!
        document.getElementById('score').textContent = `Round ${round} | Computer: ${computerScore} | You: ${humanScore}`;
        document.getElementById('result').textContent = `Draw!`;
    }

    // Case: Computer choice = rock, User choice = paper/scissor
    if (computerChoice === "rock" && humanChoice === "paper") {
        humanScore++;
        document.getElementById('score').textContent = `Round ${round} | Computer: ${computerScore} | You: ${humanScore}`;
        document.getElementById('result').textContent = `You win, Paper beats Rock`;
    }
    if (computerChoice === "rock" && humanChoice === "scissor") {
        computerScore++;
        document.getElementById('score').textContent = `Round ${round} | Computer: ${computerScore} | You: ${humanScore}`;
        document.getElementById('result').textContent = `You lose, Rock beats Scissors`;
    }

    // Case: Computer choice = paper, User choice = scissor/rock
    if (computerChoice === "paper" && humanChoice === "scissor") {
        humanScore++;
        document.getElementById('score').textContent = `Round ${round} | Computer: ${computerScore} | You: ${humanScore}`;
        document.getElementById('result').textContent = `You win, Scissor beats Paper`;
    }
    if (computerChoice === "paper" && humanChoice === "rock") {
        computerScore++;
        document.getElementById('score').textContent = `Round ${round} | Computer: ${computerScore} | You: ${humanScore}`;
        document.getElementById('result').textContent = `You lose, Paper beats Rock`;
    }

    // Case: Computer choice = scissor, User choice = rock/paper
    if (computerChoice === "scissor" && humanChoice === "rock") {
        humanScore++;
        document.getElementById('score').textContent = `Round ${round} | Computer: ${computerScore} | You: ${humanScore}`;
        document.getElementById('result').textContent = `You Win, Rock beats Scissor`;
    }
    if (computerChoice === "scissor" && humanChoice === "paper") {
        computerScore++;
        document.getElementById('score').textContent = `Round ${round} | Computer: ${computerScore} | You: ${humanScore}`;
        document.getElementById('result').textContent = `You lose, Scissor beats Paper`;
    }
}

document.getElementById('selectChoice').addEventListener('click', (e) => {
    playRound( getComputerChoice(), e.target.textContent, round );
    round++;

    // Game ends here
    if (humanScore == 5) {
        round = 1;
        humanScore = 0;
        computerScore = 0;
        document.getElementById('selectChoice').classList.add("gameResult");
        document.getElementById('selectChoice').innerText = "YOU WON THE GAME!"
        document.querySelector("p").remove();
    }
    if (computerScore == 5) {
        round = 1;
        humanScore = 0;
        computerScore = 0;
        document.getElementById('selectChoice').classList.add("gameResult");
        document.getElementById('selectChoice').innerText = "COMPUTER WON THE GAME!";
        document.querySelector("p").remove();
    }
});
