/*
    Think of random numbers generated by math.random() as outcomes as below
    ROCK - 1
    PAPER - 2
    SCISSOR - 3
*/

// These will be updated as per wins
let humanScore = 0;
let computerScore = 0;

// To get the random outcome of the three outcomes of this game
function getComputerChoice () {

    // generates a number between 1–3 (inclusive)
    let assumption = Math.floor(Math.random() * 3 + 1);

    if (assumption === 1) {
        return "rock";
    }
    if (assumption === 2) {
        return "paper";
    }
    if (assumption === 3) {
        return "scissor";
    }

}

// To get the user's choice
function getHumanChoice () {
    let input = prompt("Shoot your shot!");

    return input.toLowerCase();
}

// Function to run the game for 1 round and update scores
function playRound (computerChoice, humanChoice) {

    // Case: When both the choices are same i.e, rock/paper/scissor
    if (computerChoice === humanChoice) {
        console.log(`computer chose: ${computerChoice} and You chose: ${humanChoice}`);
        // No increment of score as it's draw!
        console.log(`computer: ${computerScore} | human: ${humanScore}`);
        return console.log(`draw`);
    }

    // Case: Computer choice = rock, User choice = paper/scissor
    if (computerChoice === "rock" && humanChoice === "paper") {
        console.log(`computer chose: ${computerChoice} and You chose: ${humanChoice}`);
        humanScore++;
        console.log(`computer: ${computerScore} | human: ${humanScore}`);
        return console.log(`You win, Paper beats Rock`);
    }
    if (computerChoice === "rock" && humanChoice === "scissor") {
        console.log(`computer chose: ${computerChoice} and You chose: ${humanChoice}`);
        computerScore++;
        console.log(`computer: ${computerScore} | human: ${humanScore}`);
        return console.log(`You lose, Rock beats Scissors`);
    }

    // Case: Computer choice = paper, User choice = scissor/rock
    if (computerChoice === "paper" && humanChoice === "scissor") {
        console.log(`computer chose: ${computerChoice} and You chose: ${humanChoice}`);
        humanScore++;
        console.log(`computer: ${computerScore} | human: ${humanScore}`);
        return console.log(`You win, Scissor beats Paper`);
    }
    if (computerChoice === "paper" && humanChoice === "rock") {
        console.log(`computer chose: ${computerChoice} and You chose: ${humanChoice}`);
        computerScore++;
        console.log(`computer: ${computerScore} | human: ${humanScore}`);
        return console.log(`You lose, Paper beats Rock`);
    }

    // Case: Computer choice = scissor, User choice = scissor/paper
    if (computerChoice === "scissor" && humanChoice === "rock") {
        console.log(`computer chose: ${computerChoice} and You chose: ${humanChoice}`);
        humanScore++;
        console.log(`computer: ${computerScore} | human: ${humanScore}`);
        return console.log(`You Win, Rock beats Scissor`);
    }
    if (computerChoice === "scissor" && humanChoice === "paper") {
        console.log(`computer chose: ${computerChoice} and You chose: ${humanChoice}`);
        computerScore++;
        console.log(`computer: ${computerScore} | human: ${humanScore}`);
        return console.log(`You lose, Scissor beats Paper`);
    }
}

// Function that loops the game upto 5 rounds with updated scores
function playGame () {
    for (let i = 0; i < 5; i++) {
        const computerSelection = getComputerChoice();
        const humanSelection = getHumanChoice();
        playRound(computerSelection, humanSelection);
    }
    
}

playGame();
